// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKvhEF60fXCrcQeC7y7mOY7ocv8maBjvU',
    appId: '1:1053183353694:web:9518dbd490b1d85938e5cf',
    messagingSenderId: '1053183353694',
    projectId: 'to-do-application-1038e',
    authDomain: 'to-do-application-1038e.firebaseapp.com',
    storageBucket: 'to-do-application-1038e.appspot.com',
    measurementId: 'G-6ZLN1XB1GD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp_owutgUCO8wXptwHdxXwXL5g7UrFcxA',
    appId: '1:1053183353694:android:1e5700fdd1804aa638e5cf',
    messagingSenderId: '1053183353694',
    projectId: 'to-do-application-1038e',
    storageBucket: 'to-do-application-1038e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBxEsqSbcAdvq96cwkxD5kXqZSRsJOyitQ',
    appId: '1:1053183353694:ios:28b1fa8e030b41a738e5cf',
    messagingSenderId: '1053183353694',
    projectId: 'to-do-application-1038e',
    storageBucket: 'to-do-application-1038e.appspot.com',
    iosClientId: '1053183353694-sf7vj2gn7fgnmjkfq5l3g8a5jjgth23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBxEsqSbcAdvq96cwkxD5kXqZSRsJOyitQ',
    appId: '1:1053183353694:ios:28b1fa8e030b41a738e5cf',
    messagingSenderId: '1053183353694',
    projectId: 'to-do-application-1038e',
    storageBucket: 'to-do-application-1038e.appspot.com',
    iosClientId: '1053183353694-sf7vj2gn7fgnmjkfq5l3g8a5jjgth23p.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDoApp',
  );
}
